/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1ma;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author godin
 */
public class Vistaadmin extends javax.swing.JFrame {
private usuario usuariologeado;

    public usuario getUsuariologeado() {
        return usuariologeado;
    }

    public void setUsuariologeado(usuario usuariologeado) {
        this.usuariologeado = usuariologeado;
    }
    /**
     * Creates new form Vistaadmin
     */
    public Vistaadmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarruta = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        GenerarBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionarruta.setText("seleccionar ruta");
        seleccionarruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarrutaActionPerformed(evt);
            }
        });

        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        GenerarBackup.setText("Generar Backup");
        GenerarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seleccionarruta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerarBackup))
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarruta)
                    .addComponent(GenerarBackup))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarrutaActionPerformed
          
          JFileChooser chooser=new JFileChooser();
         chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("Seleccionar una carpeta para hacer backup");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
   
    chooser.setAcceptAllFileFilterUsed(false);
 
  chooser.showOpenDialog(this);
      path.setText(chooser.getSelectedFile().getAbsolutePath());
      
          
    }//GEN-LAST:event_seleccionarrutaActionPerformed

    private void GenerarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarBackupActionPerformed
        File target = new File(path.getText()+"\\MEIAbackup");
        
        
       
             
                target.mkdir();
                
            try {
                
                 File sourceDirectory = new File("C:\\MEIA");
     
        
        FileUtils.copyDirectory(sourceDirectory, target);
                generarbitacora("Administrador", target.getAbsolutePath(), new Date());
                JOptionPane.showMessageDialog(null, "Backup generado exitosamente");
            
            } catch (IOException ex) {
                 JOptionPane.showMessageDialog(null, "Hubo un error al generar su Backup");
                JOptionPane.showMessageDialog(null, ex);
            }
        
        
        
    }//GEN-LAST:event_GenerarBackupActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed
  public void generarbitacora(String Usuario,String ruta,Date fecha){
      
       File f;
       
        f = new File("C:\\MEIA\\bitacora_backup.txt");
          try {
 if(!f.exists()){
        f.createNewFile();
        }
      

            FileWriter w = new FileWriter(f.getAbsoluteFile(),true);

            BufferedWriter bw = new BufferedWriter(w);

            PrintWriter wr = new PrintWriter(bw);

            wr.println(Usuario+"|"+ruta+"|"+fecha.toString());

            wr.close();

            bw.close();

        } catch (IOException e) {
        };

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistaadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarBackup;
    private javax.swing.JTextField path;
    private javax.swing.JButton seleccionarruta;
    // End of variables declaration//GEN-END:variables
}
